export const API = {
    // 全局
    // 上传文件
    uploadFile: 'https://hongyun.hopechart.com:12343/api/upload',
    // 登录
    login: '/api/login',
    // 套餐列表
    queryPackagesList: '/api/packageList',
    // 待处理订单数,待处理订单金额
    queryTodoTotal: '/api/order/todoTotal',
    // 月订单统计和累计订单统计
    queryOrderTotal: '/api/order/total',
    // 待处理汇款单数,待处理汇款单金额
    queryRemitTodoTotal: '/api/remit/todoTotal',
    // 月汇款单统计和累计汇款单统计
    queryRemitTotal: '/api/remit/total',
    // 待处理开票单数,待处理开票金额
    queryInvoiceTodoTotal: '/api/invoice/todoTotal',
    // 月开票统计和累计开票单统计
    queryInvoiceTotal: '/api/invoice/total',

    // 页面
    // sim卡管理
    querySimList: '/api/sim/list',
    // sim导出
    simExport: '/api/sim/export',
    // 文件导入记录
    querySimFileList: '/api/sim/fileList',
    // 导入文件
    importFile: '/api/sim/import',
    // sim编辑/批量
    simHandle: '/api/sim/handle',
    // 订单列表
    queryOrdersList: '/api/order/list',
    // 订单导出
    orderExport: '/api/order/export',
    // 订单处理
    orderHandle: '/api/order/handle',
    // 汇款订单列表
    queryRemitList: '/api/remit/list',
    // 汇款单审核
    remitHandle: '/api/remit/handle',
    // 充值
    addEmit: '/api/fund/recharge',
    // 开票列表
    invoiceList: '/api/invoice/list',
    // 开票处理
    invocieHandle: '/api/invoice/handle',
    // 添加发票
    addInvoice: '/api/invoice/apply',
}